# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: lint_build_preview_pr

on:
  pull_request:
    branches: [ "dev","main" ]
jobs:
  eslint:
    name: Run eslint and prettier
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "20.9.0"
          cache: 'npm'
          cache-dependency-path: AgileFront/package-lock.json
      - name: Install Eslint
        run: cd AgileFront && npm ci
      - name: Run ESlint
        run: cd AgileFront && npm run eslint
      - name: Run prettier
        run: cd AgileFront && npm run prettier
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
  build:
      name: Build app
      runs-on: ubuntu-latest
      needs: eslint
      permissions:
        contents: read
        actions: read 
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install node
          uses: actions/setup-node@v4.0.0
          with:
            node-version: "20.9.0"
            cache: 'npm'
            cache-dependency-path: AgileFront/package-lock.json
        - name: Install Angular
          run: npm install -g @angular/cli
        - name: Install dependencies
          run: cd AgileFront && npm ci
        - name: Build
          run: cd AgileFront && ng build
        - name: Archive Artifacts
          uses: actions/upload-artifact@v3.1.3
          with:
            name: dist
            path: AgileFront/dist
  preview:
    name: Deploy preview
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: dist
          path: AgileFront/dist
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0.5-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGILEBACKEND }}"
          expires: 30d
          projectId: agilebackend-9e4d6
          entryPoint: AgileFront
          
            
        
